"""baseline

Revision ID: 796321fd1c74
Revises:
Create Date: 2026-01-11 01:00:51.365231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796321fd1c74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_templates_category'), 'consultation_templates', ['category'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_key'), 'document_templates', ['key'], unique=True)
    op.create_table('knowledge_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('law_firms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('specialties', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('article_number', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('is_vectorized', sa.Boolean(), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_knowledge_category'), 'legal_knowledge', ['category'], unique=False)
    op.create_index(op.f('ix_legal_knowledge_knowledge_type'), 'legal_knowledge', ['knowledge_type'], unique=False)
    op.create_index(op.f('ix_legal_knowledge_title'), 'legal_knowledge', ['title'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=40), nullable=True),
    sa.Column('source_site', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_unpublish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_dedupe_hash', 'news', ['dedupe_hash'], unique=False)
    op.create_index('ix_news_published_review', 'news', ['is_published', 'review_status'], unique=False)
    op.create_index('ix_news_review_status', 'news', ['review_status'], unique=False)
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('fetch_timeout_seconds', sa.Float(), nullable=True),
    sa.Column('max_items_per_feed', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url', name='uq_news_sources_feed_url')
    )
    op.create_index('ix_news_sources_enabled', 'news_sources', ['is_enabled'], unique=False)
    op.create_index('ix_news_sources_type', 'news_sources', ['source_type'], unique=False)
    op.create_table('news_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('auto_category', sa.String(length=50), nullable=True),
    sa.Column('auto_keyword', sa.String(length=100), nullable=True),
    sa.Column('auto_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('avg_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_date'), 'page_views', ['date'], unique=False)
    op.create_index(op.f('ix_page_views_page'), 'page_views', ['page'], unique=False)
    op.create_table('payment_callback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=True),
    sa.Column('trade_no', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=200), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'trade_no', name='uq_payment_cb_provider_trade_no')
    )
    op.create_index(op.f('ix_payment_callback_events_order_no'), 'payment_callback_events', ['order_no'], unique=False)
    op.create_index(op.f('ix_payment_callback_events_provider'), 'payment_callback_events', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_callback_events_trade_no'), 'payment_callback_events', ['trade_no'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vip_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_logs_user_id'), 'admin_logs', ['user_id'], unique=False)
    op.create_table('calendar_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_reminders_due_at'), 'calendar_reminders', ['due_at'], unique=False)
    op.create_index(op.f('ix_calendar_reminders_is_done'), 'calendar_reminders', ['is_done'], unique=False)
    op.create_index(op.f('ix_calendar_reminders_remind_at'), 'calendar_reminders', ['remind_at'], unique=False)
    op.create_index(op.f('ix_calendar_reminders_user_id'), 'calendar_reminders', ['user_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_session_id'), 'consultations', ['session_id'], unique=True)
    op.create_table('document_template_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_document_template_versions_template_version')
    )
    op.create_index(op.f('ix_document_template_versions_is_published'), 'document_template_versions', ['is_published'], unique=False)
    op.create_index(op.f('ix_document_template_versions_template_id'), 'document_template_versions', ['template_id'], unique=False)
    op.create_index(op.f('ix_document_template_versions_version'), 'document_template_versions', ['version'], unique=False)
    op.create_table('feedback_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_tickets_status'), 'feedback_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_tickets_user_id'), 'feedback_tickets', ['user_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_document_type'), 'generated_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_generated_documents_template_key'), 'generated_documents', ['template_key'], unique=False)
    op.create_index(op.f('ix_generated_documents_user_id'), 'generated_documents', ['user_id'], unique=False)
    op.create_table('lawyer_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=False),
    sa.Column('id_card_no', sa.String(length=20), nullable=False),
    sa.Column('license_no', sa.String(length=100), nullable=False),
    sa.Column('firm_name', sa.String(length=200), nullable=False),
    sa.Column('id_card_front', sa.String(length=255), nullable=True),
    sa.Column('id_card_back', sa.String(length=255), nullable=True),
    sa.Column('license_photo', sa.String(length=255), nullable=True),
    sa.Column('specialties', sa.String(length=500), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('specialties', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_ai_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('sensitive_words', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('duplicate_of_news_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', name='uq_news_ai_annotations_news')
    )
    op.create_index('ix_news_ai_annotations_processed_at', 'news_ai_annotations', ['processed_at'], unique=False)
    op.create_index('ix_news_ai_annotations_risk_level', 'news_ai_annotations', ['risk_level'], unique=False)
    op.create_table('news_ai_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_ai_generations_created_at'), 'news_ai_generations', ['created_at'], unique=False)
    op.create_index('ix_news_ai_generations_news_created', 'news_ai_generations', ['news_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_news_ai_generations_news_id'), 'news_ai_generations', ['news_id'], unique=False)
    op.create_index('ix_news_ai_generations_user_created', 'news_ai_generations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_news_ai_generations_user_id'), 'news_ai_generations', ['user_id'], unique=False)
    op.create_table('news_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_comments_created_at'), 'news_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_comments_news_id'), 'news_comments', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_comments_user_id'), 'news_comments', ['user_id'], unique=False)
    op.create_table('news_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'user_id', name='uq_news_favorite_news_user')
    )
    op.create_table('news_ingest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('feed_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_ingest_runs_created_at'), 'news_ingest_runs', ['created_at'], unique=False)
    op.create_index('ix_news_ingest_runs_source_created', 'news_ingest_runs', ['source_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_news_ingest_runs_source_id'), 'news_ingest_runs', ['source_id'], unique=False)
    op.create_index('ix_news_ingest_runs_status_created', 'news_ingest_runs', ['status', 'created_at'], unique=False)
    op.create_table('news_link_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('final_url', sa.String(length=800), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_link_checks_checked_at'), 'news_link_checks', ['checked_at'], unique=False)
    op.create_index('ix_news_link_checks_news_checked', 'news_link_checks', ['news_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_news_link_checks_news_id'), 'news_link_checks', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_link_checks_run_id'), 'news_link_checks', ['run_id'], unique=False)
    op.create_index('ix_news_link_checks_run_url', 'news_link_checks', ['run_id', 'url'], unique=False)
    op.create_index(op.f('ix_news_link_checks_user_id'), 'news_link_checks', ['user_id'], unique=False)
    op.create_table('news_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sub_type', 'value', name='uq_news_subscriptions_user_type_value')
    )
    op.create_index('ix_news_subscriptions_user', 'news_subscriptions', ['user_id'], unique=False)
    op.create_table('news_topic_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'news_id', name='uq_news_topic_items_topic_news')
    )
    op.create_index('ix_news_topic_items_news', 'news_topic_items', ['news_id'], unique=False)
    op.create_index('ix_news_topic_items_topic', 'news_topic_items', ['topic_id'], unique=False)
    op.create_table('news_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_versions_created_at'), 'news_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_versions_created_by'), 'news_versions', ['created_by'], unique=False)
    op.create_index('ix_news_versions_news_created', 'news_versions', ['news_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_news_versions_news_id'), 'news_versions', ['news_id'], unique=False)
    op.create_table('news_view_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'user_id', name='uq_news_view_history_news_user')
    )
    op.create_index('ix_news_view_history_user_viewed_at', 'news_view_history', ['user_id', 'viewed_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('related_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'dedupe_key', name='uq_notifications_user_type_dedupe_key')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('actual_amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('trade_no', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_order_no'), 'payment_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('is_essence', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('review_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heat_score', sa.Float(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_keyword'), 'search_history', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('page', sa.String(length=200), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_action'), 'user_activities', ['action'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_session_id'), 'user_activities', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('user_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('frozen', sa.Float(), nullable=False),
    sa.Column('total_recharged', sa.Float(), nullable=False),
    sa.Column('total_consumed', sa.Float(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=True),
    sa.Column('frozen_cents', sa.Integer(), nullable=True),
    sa.Column('total_recharged_cents', sa.Integer(), nullable=True),
    sa.Column('total_consumed_cents', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_version', sa.String(length=50), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doc_type', 'doc_version', name='uq_user_consents_user_doc_ver')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('user_quota_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ai_chat_count', sa.Integer(), nullable=False),
    sa.Column('document_generate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_user_quota_daily_user_day')
    )
    op.create_index(op.f('ix_user_quota_daily_day'), 'user_quota_daily', ['day'], unique=False)
    op.create_index(op.f('ix_user_quota_daily_user_id'), 'user_quota_daily', ['user_id'], unique=False)
    op.create_table('user_quota_pack_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_chat_credits', sa.Integer(), nullable=False),
    sa.Column('document_generate_credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_quota_pack_balances_user_id')
    )
    op.create_index(op.f('ix_user_quota_pack_balances_user_id'), 'user_quota_pack_balances', ['user_id'], unique=False)
    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('balance_before_cents', sa.Integer(), nullable=True),
    sa.Column('balance_after_cents', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_transactions_user_id'), 'balance_transactions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('review_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyer_bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_no', sa.String(length=100), nullable=False),
    sa.Column('account_holder', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_bank_accounts_lawyer_id'), 'lawyer_bank_accounts', ['lawyer_id'], unique=False)
    op.create_table('lawyer_consultations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyer_wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('withdrawn_amount', sa.Float(), nullable=False),
    sa.Column('pending_amount', sa.Float(), nullable=False),
    sa.Column('frozen_amount', sa.Float(), nullable=False),
    sa.Column('available_amount', sa.Float(), nullable=False),
    sa.Column('total_income_cents', sa.Integer(), nullable=True),
    sa.Column('withdrawn_amount_cents', sa.Integer(), nullable=True),
    sa.Column('pending_amount_cents', sa.Integer(), nullable=True),
    sa.Column('frozen_amount_cents', sa.Integer(), nullable=True),
    sa.Column('available_amount_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_wallets_lawyer_id'), 'lawyer_wallets', ['lawyer_id'], unique=True)
    op.create_table('post_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_favorite_post_user')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like_post_user')
    )
    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'emoji', name='uq_post_reaction')
    )
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_no', sa.String(length=64), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('fee_cents', sa.Integer(), nullable=True),
    sa.Column('actual_amount_cents', sa.Integer(), nullable=True),
    sa.Column('withdraw_method', sa.String(length=20), nullable=False),
    sa.Column('account_info', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no', name='uq_withdraw_request_no')
    )
    op.create_index(op.f('ix_withdrawal_requests_lawyer_id'), 'withdrawal_requests', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_request_no'), 'withdrawal_requests', ['request_no'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_status'), 'withdrawal_requests', ['status'], unique=False)
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_like_comment_user')
    )
    op.create_table('lawyer_consultation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['lawyer_consultations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_consultation_messages_consultation_id'), 'lawyer_consultation_messages', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_lawyer_consultation_messages_sender_user_id'), 'lawyer_consultation_messages', ['sender_user_id'], unique=False)
    op.create_table('lawyer_income_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('order_no', sa.String(length=64), nullable=True),
    sa.Column('user_paid_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('lawyer_income', sa.Float(), nullable=False),
    sa.Column('user_paid_amount_cents', sa.Integer(), nullable=True),
    sa.Column('platform_fee_cents', sa.Integer(), nullable=True),
    sa.Column('lawyer_income_cents', sa.Integer(), nullable=True),
    sa.Column('withdrawn_amount', sa.Float(), nullable=False),
    sa.Column('withdrawn_amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settle_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['lawyer_consultations.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_income_records_consultation_id'), 'lawyer_income_records', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_lawyer_income_records_lawyer_id'), 'lawyer_income_records', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_lawyer_income_records_order_no'), 'lawyer_income_records', ['order_no'], unique=False)
    op.create_index(op.f('ix_lawyer_income_records_status'), 'lawyer_income_records', ['status'], unique=False)
    op.create_table('lawyer_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['lawyer_consultations.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lawyer_reviews')
    op.drop_index(op.f('ix_lawyer_income_records_status'), table_name='lawyer_income_records')
    op.drop_index(op.f('ix_lawyer_income_records_order_no'), table_name='lawyer_income_records')
    op.drop_index(op.f('ix_lawyer_income_records_lawyer_id'), table_name='lawyer_income_records')
    op.drop_index(op.f('ix_lawyer_income_records_consultation_id'), table_name='lawyer_income_records')
    op.drop_table('lawyer_income_records')
    op.drop_index(op.f('ix_lawyer_consultation_messages_sender_user_id'), table_name='lawyer_consultation_messages')
    op.drop_index(op.f('ix_lawyer_consultation_messages_consultation_id'), table_name='lawyer_consultation_messages')
    op.drop_table('lawyer_consultation_messages')
    op.drop_table('comment_likes')
    op.drop_index(op.f('ix_withdrawal_requests_status'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_request_no'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_lawyer_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_table('post_reactions')
    op.drop_table('post_likes')
    op.drop_table('post_favorites')
    op.drop_index(op.f('ix_lawyer_wallets_lawyer_id'), table_name='lawyer_wallets')
    op.drop_table('lawyer_wallets')
    op.drop_table('lawyer_consultations')
    op.drop_index(op.f('ix_lawyer_bank_accounts_lawyer_id'), table_name='lawyer_bank_accounts')
    op.drop_table('lawyer_bank_accounts')
    op.drop_table('comments')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_balance_transactions_user_id'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    op.drop_index(op.f('ix_user_quota_pack_balances_user_id'), table_name='user_quota_pack_balances')
    op.drop_table('user_quota_pack_balances')
    op.drop_index(op.f('ix_user_quota_daily_user_id'), table_name='user_quota_daily')
    op.drop_index(op.f('ix_user_quota_daily_day'), table_name='user_quota_daily')
    op.drop_table('user_quota_daily')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_table('user_balances')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_session_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_action'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_keyword'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_table('posts')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_order_no'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_news_view_history_user_viewed_at', table_name='news_view_history')
    op.drop_table('news_view_history')
    op.drop_index(op.f('ix_news_versions_news_id'), table_name='news_versions')
    op.drop_index('ix_news_versions_news_created', table_name='news_versions')
    op.drop_index(op.f('ix_news_versions_created_by'), table_name='news_versions')
    op.drop_index(op.f('ix_news_versions_created_at'), table_name='news_versions')
    op.drop_table('news_versions')
    op.drop_index('ix_news_topic_items_topic', table_name='news_topic_items')
    op.drop_index('ix_news_topic_items_news', table_name='news_topic_items')
    op.drop_table('news_topic_items')
    op.drop_index('ix_news_subscriptions_user', table_name='news_subscriptions')
    op.drop_table('news_subscriptions')
    op.drop_index(op.f('ix_news_link_checks_user_id'), table_name='news_link_checks')
    op.drop_index('ix_news_link_checks_run_url', table_name='news_link_checks')
    op.drop_index(op.f('ix_news_link_checks_run_id'), table_name='news_link_checks')
    op.drop_index(op.f('ix_news_link_checks_news_id'), table_name='news_link_checks')
    op.drop_index('ix_news_link_checks_news_checked', table_name='news_link_checks')
    op.drop_index(op.f('ix_news_link_checks_checked_at'), table_name='news_link_checks')
    op.drop_table('news_link_checks')
    op.drop_index('ix_news_ingest_runs_status_created', table_name='news_ingest_runs')
    op.drop_index(op.f('ix_news_ingest_runs_source_id'), table_name='news_ingest_runs')
    op.drop_index('ix_news_ingest_runs_source_created', table_name='news_ingest_runs')
    op.drop_index(op.f('ix_news_ingest_runs_created_at'), table_name='news_ingest_runs')
    op.drop_table('news_ingest_runs')
    op.drop_table('news_favorites')
    op.drop_index(op.f('ix_news_comments_user_id'), table_name='news_comments')
    op.drop_index(op.f('ix_news_comments_news_id'), table_name='news_comments')
    op.drop_index(op.f('ix_news_comments_created_at'), table_name='news_comments')
    op.drop_table('news_comments')
    op.drop_index(op.f('ix_news_ai_generations_user_id'), table_name='news_ai_generations')
    op.drop_index('ix_news_ai_generations_user_created', table_name='news_ai_generations')
    op.drop_index(op.f('ix_news_ai_generations_news_id'), table_name='news_ai_generations')
    op.drop_index('ix_news_ai_generations_news_created', table_name='news_ai_generations')
    op.drop_index(op.f('ix_news_ai_generations_created_at'), table_name='news_ai_generations')
    op.drop_table('news_ai_generations')
    op.drop_index('ix_news_ai_annotations_risk_level', table_name='news_ai_annotations')
    op.drop_index('ix_news_ai_annotations_processed_at', table_name='news_ai_annotations')
    op.drop_table('news_ai_annotations')
    op.drop_table('lawyers')
    op.drop_table('lawyer_verifications')
    op.drop_index(op.f('ix_generated_documents_user_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_template_key'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_document_type'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_feedback_tickets_user_id'), table_name='feedback_tickets')
    op.drop_index(op.f('ix_feedback_tickets_status'), table_name='feedback_tickets')
    op.drop_table('feedback_tickets')
    op.drop_index(op.f('ix_document_template_versions_version'), table_name='document_template_versions')
    op.drop_index(op.f('ix_document_template_versions_template_id'), table_name='document_template_versions')
    op.drop_index(op.f('ix_document_template_versions_is_published'), table_name='document_template_versions')
    op.drop_table('document_template_versions')
    op.drop_index(op.f('ix_consultations_session_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_calendar_reminders_user_id'), table_name='calendar_reminders')
    op.drop_index(op.f('ix_calendar_reminders_remind_at'), table_name='calendar_reminders')
    op.drop_index(op.f('ix_calendar_reminders_is_done'), table_name='calendar_reminders')
    op.drop_index(op.f('ix_calendar_reminders_due_at'), table_name='calendar_reminders')
    op.drop_table('calendar_reminders')
    op.drop_index(op.f('ix_admin_logs_user_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_callback_events_trade_no'), table_name='payment_callback_events')
    op.drop_index(op.f('ix_payment_callback_events_provider'), table_name='payment_callback_events')
    op.drop_index(op.f('ix_payment_callback_events_order_no'), table_name='payment_callback_events')
    op.drop_table('payment_callback_events')
    op.drop_index(op.f('ix_page_views_page'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_date'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_table('news_topics')
    op.drop_index('ix_news_sources_type', table_name='news_sources')
    op.drop_index('ix_news_sources_enabled', table_name='news_sources')
    op.drop_table('news_sources')
    op.drop_index('ix_news_review_status', table_name='news')
    op.drop_index('ix_news_published_review', table_name='news')
    op.drop_index('ix_news_dedupe_hash', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_legal_knowledge_title'), table_name='legal_knowledge')
    op.drop_index(op.f('ix_legal_knowledge_knowledge_type'), table_name='legal_knowledge')
    op.drop_index(op.f('ix_legal_knowledge_category'), table_name='legal_knowledge')
    op.drop_table('legal_knowledge')
    op.drop_table('law_firms')
    op.drop_table('knowledge_categories')
    op.drop_index(op.f('ix_document_templates_key'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_consultation_templates_category'), table_name='consultation_templates')
    op.drop_table('consultation_templates')
    # ### end Alembic commands ###
